# Build and Push Hugo site to gh-pages
name: build-push

# trigger events
on:
  workflow_dispatch:
    
  push:
    branches:
      - 'main'
    paths-ignore:
      - ".docker/**"
      - ".example/**"
      - ".github/**"
      - "README.md"
      - "*.txt"
      - "*.sh"
      - "images/**"
      - "docker-compose.yml"
    

jobs:
  
  # Build & Push hugo site
  hugo:
    runs-on: ubuntu-latest
    steps:

      # Pull Source Code
      - name: ✅ Checkout Source
        uses: actions/checkout@v2

      - name: 🔨 Build Hugo Site
        run: |
          cp .env.example .env
          sh build.sh --baseUrl https://acknologyhq.github.io/impact-hugo/

      - name: ℹ️ Setup files in dist
        run: |
          cp README.md dist/dist-readme.md

      - name: 🚀 Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          MESSAGE: "🔨 Build gh-pages from {target-branch} {sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}